version: '1.0.{build}'
configuration:
#- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- msbuild
after_build:
- robocopy "WatermarkingDemo\bin\%CONFIGURATION%" "artifacts\WatermarkingDemo"
artifacts:
- path: artifacts\**\*.*
test:
  # only assemblies to test
  assemblies:
    only:
      - 'HiddenWatermark.Tests\bin\%CONFIGURATION%\HiddenWatermark.Tests.dll'
